- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy webserver configuration
  template:
    src: webserver_config.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - Restart Nginx
